# path to contigs folder
fasta_folder: /data/san/data1/users/remi/Proteins

# Extension of the file
extension: prt

# path to the result folder
output_folder: /data/san/data1/users/remi/macsyfinder_TXSScan_stats_v1

# Type of replicon choose between {ordered_replicon,gembase,unordered}
db_type: gembase

# Topology of the replicon: {linear,circular}
replicon_topology: circular

# Folder with the models
macsydata_def: /data/san/data1/users/remi/macsyfinder_snakemake_v1/config/macsydata/TXSScan/definitions
macsydata_profile: /data/san/data1/users/remi/macsyfinder_snakemake_v1/config/macsydata/TXSScan/profiles

# Models to search in a tsv file, first columns name of the replicon second the models with an header
models_tsv: config/replicon_models.all.tsv

# Default models if no model provide in the tsv
models: all

# Binary to macsyfinder
macsyfinder: /data/san/data1/users/remi/macsyfinder_snakemake_v1/config/macsyfinder_v1/macsyfinder
